# Generated by Django 5.1.15 on 2026-08-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('current', 'Current'), ('upcoming', 'Upcoming')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'roadmap_stages',
                'ordering': ['order'],
            },
        ),
    ]
