# Generated by Django 6.1 on 2026-09-03 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapstage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roadmapstage',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='roadmapstage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='RoadmapSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('current', 'Current'), ('upcoming', 'Upcoming')], max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='roadmaps.roadmapstage')),
            ],
            options={
                'db_table': 'roadmap_skills',
            },
        ),
    ]
