# Generated by Django 5.1.15 on 2026-08-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('career_name', models.CharField(max_length=150)),
                ('match_percent', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('matched_skills', models.CharField(blank=True, max_length=300)),
                ('missing_skills', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'career_recommendations',
            },
        ),
    ]
