# Generated by Django 6.1 on 2026-09-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'career_definitions',
            },
        ),
    ]
