# Generated by Django 5.1.15 on 2026-08-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('skill', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('completed_lessons', models.PositiveIntegerField(default=0)),
                ('total_lessons', models.PositiveIntegerField(default=1)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('ai_recommended', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
